### PR TITLE
Various improvements and performance gains

### PR DESCRIPTION
**Pull request by flovilmart**
Final part of refactoring #6 in multiple parts:

- Better performance for loading
- Option to add breakpoint just after spec being run (useful in some cases, off by default)

### CODE REVIEW

**Comment by flovilmart** [comment]
Do you have a code example for me to test?

**Comment by hbenl** [comment]
```
describe("Top suite 1", function() {

    it("A Test", function() {});

});

describe("Top suite 2", function() {
    
});

it("Top test", function() {

});
```

This time the empty top-level suite shows up but still doesn't get a Code Lens. The top-level test still doesn't show up.

**Comment by flovilmart** [comment]
Ok cool! Thanks, I believe I know what’s what :)

**Comment by flovilmart** [comment]
@hbenl I ended up refactoring it all. The reporter now reports exacly 1 suite per file, this way it's cleaner an easier to manage. It also reduces the amount of logic in the adapter, which is way better as it was getting hairy.

For now the reporter keeps track of the file that is being processed, and when the file changes, it emits the full suite for the file.

I tested on the small project as well as a very large one. Because jasmine loads it all in order, there's no need to do additional sorting.

**Comment by hbenl** [comment]
For me the top level elements (tests and suites) still don't get a Code Lens because their location is reported as the last line of the file. I debugged into `loadTestsUtils.ts` and found that the loop for finding the "highest call site" is to blame: the first loop (at line 8) finds the correct stackLine, but then the loop at line 22 decides that the next stackLine should be used - and that references the last line of the test file. If I simply remove that loop, it all works fine for me... but I guess you have an example where that loop is needed!?

> Because jasmine loads it all in order, there's no need to do additional sorting.

Well, if the user sets `"random": true` in his `jasmine.json` then the order of the tests is randomized and the tests and suites jump around in the explorer on every reload.

**Comment by flovilmart** [comment]
>  If I simply remove that loop, it all works fine for me... but I guess you have an example where that loop is needed!?

Yeah can you provide your stacklines so I can identify what's what (and possibly a test example)? The goal in this one is to ensure we're going as high in the stack as possible and still be in the file. You're right, perhaps it should keep the original line if it goes through all the stack without finding anyting.

**Comment by hbenl** [comment]
The example is still the one I gave above. Here's the stacktrace for `it("Top test", ...)`

```
Error
    at getStackLineMatching (/home/marvin/Misc/projects/test-explorer/vscode-jasmine-test-adapter/out/worker/loadTestsUtils.js:4:17)
    at Env.specPatch [as it] (/home/marvin/Misc/projects/test-explorer/vscode-jasmine-test-adapter/out/worker/loadTestsUtils.js:59:30)
    at it (/home/marvin/Misc/projects/test-explorer/vscode-jasmine-test-adapter/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:5022:21)
    at Object.<anonymous> (/home/marvin/Misc/projects/test-explorer/testproject3/spec/jasmine_examples/TopLevelTestSpec.js:11:1)
    at Object.<anonymous> (/home/marvin/Misc/projects/test-explorer/testproject3/spec/jasmine_examples/TopLevelTestSpec.js:15:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
> perhaps it should keep the original line if it goes through all the stack without finding anyting

Just to clarify: that second loop *does* find something (the line containing `TopLevelTestSpec.js:15:3`), but the first loop finds the line containing `TopLevelTestSpec.js:11:1`, which is the correct one.

**Comment by flovilmart** [comment]
ok... that kinda put everything back on the ground :/ as there's nothing on line 15

In the last commit, I just fixed the ordering, but I can't really repro the issue where the line used would be 15 :/
capture d ecran le 2018-07-03 a 14 06 23

**Comment by hbenl** [comment]
Hmmm... so the stacktrace apparently depends on the platform and/or the node version - because everything else should be the same on your machine and mine.
Anyway, can you give me an example where the second loop in `getStackLineMatching()` is necessary? Because I would expect the first loop to already find the correct line.

**Comment by flovilmart** [comment]
In this example, I removed the second loop, as you can see, it's stuck on the it.

capture d ecran le 2018-07-03 a 15 52 29

**Comment by flovilmart** [comment]
And I have managed to reproduce your use case::

```
(function() {
  it('shoud be found', () => {});

  it('should be found too..', () => {});
})();
```

As the `it` is wrapped into an anonymous function, which can be that depending on the module loader.

I need to find a better way to get those in. The 1st pass should be enough usually, but thenm the second is needed for our project ;)

**Comment by hbenl** [comment]
I think I found how you can reproduce this: my setup was using the node version shipped with VS Code. So if you set `"jasmineExplorer.nodePath": null` in your test project you should get the same result as me.
When I removed that line from my configuration, I got the same results as you. But in that case I could also remove the second loop and still get the same result.

**Comment by flovilmart** [comment]
Yeah, I changed the implementation in our project to return ‘it’ instead of calling ‘it’ from the wrapper. And it’s just fine.

**Pull request merged**
